config/routes.rb
ShopScaffold::Application.routes.draw do

  root to: 'catalogs#index'

  resources :categories, :except => [:show]
  resources :orders
  resources :carts
  resources :line_items
  resources :sessions,   :only   => [:new, :create, :destroy]
  resources :products,   :except => [:show]
  resources :catalogs
  resources :feedbacks

  match '/catalog',     :to => 'catalogs#index', :as => 'catalog'
  match '/catalog/:id', :to => 'catalogs#show',  :as => 'our_product'

  post '/users/change_role'
  post '/sessions/change_locale', as: 'locale'
  get  '/store/index',            as: 'store'
  get  '/shallow/search',         as: 'search'

  match '/admin_profile', to: 'pages#admin_profile'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy'

end

app/views/shared/_cart.erb
<% if @cart.empty? %>
  <h3 class="sidebar_title"><%= t("cart_is_empty") %></h3>
<% else %>
  <h3 class="sidebar_title"><%= t("cart") %></h3>
  <% @cart.line_items.each do |item| %>
    <a class="item" id="<%= "current_item" if item == @current_item %>" href="<%= our_product_path(item.product) %>">
      <%= "#{cut item.title, 20} (#{item.quantity})" %>
      <span class="count"><%= to_grn item.total_price %></span>
    </a>
  <% end %>
  <div class="item cart_totals">
    <%= "#{t('totals')} (#{@cart.total_quantity})" %>
    <span class="count"><%= to_grn @cart.total_price %></span>
  </div>
  <%= button_to t('checkout'), cart_path(@cart), method: :get, class: "button blue", style:"width: 45%; display:inline; float: right" %>
  <%= button_to t('empty_cart'), @cart, method: :delete, confirm: t('are_you_sure'), class: "button blue", style:"width: 45%; display:inline; float: left" %>
<% end %>

app/views/shared/_error_messages.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h4><%= t('there_where_the_problems_with_following_fields')%></h4>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_messages.erb
<div class="flash_box">
  <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><span>X</span><%= value %></div>
  <% end %>
</div>

app/views/shared/_signin_window.erb
<div id="signin_window">
  <h3><%= t('enter_for_admin')%></h3>
    <%= form_for(:session, :url => sessions_path) do |f| %>
      <%= f.label :email %><br />
      <%= f.text_field :email %>
      <%= f.label t('password') %><br />
      <%= f.password_field :password %>
      <%= f.submit t('sign_in') %>
    <% end %>
</div>