config/routes.rb
ShopScaffold::Application.routes.draw do

  root to: 'catalogs#index'

  resources :categories, :except => [:show]
  resources :orders
  resources :carts
  resources :line_items
  resources :sessions,   :only   => [:new, :create, :destroy]
  resources :products,   :except => [:show]
  resources :catalogs
  resources :feedbacks

  match '/catalog',     :to => 'catalogs#index', :as => 'catalog'
  match '/catalog/:id', :to => 'catalogs#show',  :as => 'our_product'

  post '/users/change_role'
  post '/sessions/change_locale', as: 'locale'
  get  '/store/index',            as: 'store'
  get  '/shallow/search',         as: 'search'

  match '/admin_profile', to: 'pages#admin_profile'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy'

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
  validates_presence_of :name
  validates :name, :length => { :maximum => 25 }
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :is_admin?

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    @category.save ? redirect_to(categories_path, notice: t('category_created')) : render(:new)
  end

  def update
    @category = Category.find(params[:id])
    @category.update_attributes(params[:category]) ?
        redirect_to(categories_path, notice: t('category_updated')) :
        render(:edit)
  end

  def destroy
    Category.find(params[:id]).destroy and redirect_to categories_path
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper

  def categories_names
    cat_names = []
    Category.all.each  do |cat|
      cat_names << cat.name
    end
    cat_names
  end

end

app/views/categories/_form.html.erb
<%= form_for @category  do |f| %>
  <div class="form_fields">
    <%= f.label "Название" %><br>
    <%= f.text_field :name %><br>
    <%= submit_tag "ГОТОВО" %>
  </div>
  <div class="form_errors">
    <%= render 'shared/error_messages', :object => f.object %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Перейменование категории</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Категории товаров</h1>
<%= link_to 'Добавить новую категорию', new_category_path, class: "button blue float_right", id: "new_category" %>
<br>
<table>
  <tr>
    <th>Категория</th>
    <th>Количество товаров</th>
    <th></th>
  </tr>
<% @categories.each do |category| %>
  <tr onclick="window.location = '<%= edit_category_url(category) %>'">
    <td><%= category.name %></td>
    <td width="250px"><%= category.products.length %></td>
    <td width="250px" class="admin_table_actions"><%= link_to "Удалить", category_path(category),  method: :delete, confirm: "Точно?", class: "delete_action" %></td>
  </tr>
<% end %>
</table>

app/views/categories/new.html.erb
<h1>Новая категория</h1>

<%= render 'form' %>