config/routes.rb
ShopScaffold::Application.routes.draw do

  root to: 'catalogs#index'

  resources :categories, :except => [:show]
  resources :orders
  resources :carts
  resources :line_items
  resources :sessions,   :only   => [:new, :create, :destroy]
  resources :products,   :except => [:show]
  resources :catalogs
  resources :feedbacks

  match '/catalog',     :to => 'catalogs#index', :as => 'catalog'
  match '/catalog/:id', :to => 'catalogs#show',  :as => 'our_product'

  post '/users/change_role'
  post '/sessions/change_locale', as: 'locale'
  get  '/store/index',            as: 'store'
  get  '/shallow/search',         as: 'search'

  match '/admin_profile', to: 'pages#admin_profile'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :line_items
  has_many :orders, through: :line_items

  attr_accessible :description, :title, :price, :category_id, :image, :archived

  has_attached_file :image, :styles => {:small => "100x100>", :medium => "250x250>" },
                            :url  => "/product_images/:id/:style/:basename.:extension",
                            :path => ":rails_root/public/product_images/:id/:style/:basename.:extension"

  validates :title,       :presence => true, :length => { :maximum => 30 }
  validates :description, :presence => true
  validates :price,       :presence => true, :numericality => {greater_than_or_equal_to: 0.01}

  validates_attachment_presence :image
  validates_attachment_size :image, :less_than => 10.megabytes
  validates_attachment_content_type :image, :content_type => %w(image/jpeg image/png image/jpg image/gif)

  default_scope :order => 'created_at DESC'

  def self.paginate_with_conditions(per_page=10, page=1, conditions=nil)
    paginate :per_page => per_page, :page => page, :conditions => conditions
  end

  def exist_in_order?
    not LineItem.where(:product_id => id).nil?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_filter :is_admin?

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @categories = Category.all
  end

  def edit
    @product = Product.find params[:id]
    @categories = Category.all
  end

  def create
    @product  = Product.new params[:product]
    if @product.save
      flash[:success] = t('product_created')
      redirect_to products_path
    else
      @categories = Category.all
      render :new
    end
  end

  def update
    @product = Product.find params[:id]
    if @product.update_attributes(params[:product])
      redirect_to products_path, :notice => t('product_updated')
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find params[:id]
    @product.exist_in_order? ? @product.update_attribute(:archived, true) : @product.destroy
    redirect_to :back
  end

end

app/views/products/_form.html.erb
<%= form_for(@product, :html => {multipart: true}) do |f| %>
  <div class="form_fields">
    <%= f.label "Название" %><br>
    <%= f.text_field :title %>
    <br>
    <%= f.label "Описание товара" %><br>
    <%= f.text_area :description, rows: 8 %>
    <br>
    <%= f.label "Цена" %><br>
    <%= f.text_field :price %>
    <br>
    <%= f.label "Категория" %><br >
    <%= f.collection_select :category_id, @categories, :id, :name if @categories %>
    <br>
    <%= image_tag @product.image.url :medium unless @product.image_file_name.nil? %><br>
    <%= f.file_field :image, class: "with_file_name_label" %><br>
    <%= submit_tag "ГОТОВО" %>
  </div>
  <div class="form_errors">
    <%= render 'shared/error_messages', :object => f.object %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Изменение атрибутов продукта</h1>

<%= render 'form' %>

app/views/products/index.html.erb
<h1>
  <% if @products.length > 0 %>
    Список всех товаров (<%= @products.length %>)
  <% else %>
    У Вас пока нет ни одного продукта!
  <% end %>
</h1>
<%= link_to "Создать новый товар", new_product_path, class: "button blue float_right", id: "new_product" %>
<br>
<% if @products.present? %>
  <table>
    <tr>
      <th>Картинка</th>
      <th>Название</th>
      <th>Описание</th>
      <th>Цена</th>
      <th>Категория</th>
      <th></th>
    </tr>
    <% @products.each do |product| %>
      <tr onclick="window.location = '<%= edit_product_url(product) %>'">
        <td><%= image_tag product.image.url :small %></td>
        <td class="title"><%= product.title %></td>
        <td><%= product.description %></td>
        <td class="currency"><%= "#{number_to_currency product.price, unit: ''} грн." %></td>
        <td><%= product.category ? product.category.name : "Нету" %></td>
        <td width="250px" class="admin_table_actions">
          <%= link_to "Удалить", product_path(product), :method => :delete, confirm: "Точно?", class: "delete_action" %>
        </td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/products/new.html.erb
<h1>Добавление товара</h1>
<br><br>
<%= render 'form' %>