config/routes.rb
ShopScaffold::Application.routes.draw do

  root to: 'catalogs#index'

  resources :categories, :except => [:show]
  resources :orders
  resources :carts
  resources :line_items
  resources :sessions,   :only   => [:new, :create, :destroy]
  resources :products,   :except => [:show]
  resources :catalogs
  resources :feedbacks

  match '/catalog',     :to => 'catalogs#index', :as => 'catalog'
  match '/catalog/:id', :to => 'catalogs#show',  :as => 'our_product'

  post '/users/change_role'
  post '/sessions/change_locale', as: 'locale'
  get  '/store/index',            as: 'store'
  get  '/shallow/search',         as: 'search'

  match '/admin_profile', to: 'pages#admin_profile'
  match '/signin',        to: 'sessions#new'
  match '/signout',       to: 'sessions#destroy'

end

app/views/layouts/_cap.erb
<div id="cap">
  <%= form_tag catalog_path, id: "search_form" do %>
    <%= text_field_tag :search_value, "", placeholder: t('search')%>
    <%= submit_tag '', id: "search_submit", title: t('search'), name: "search"%>
  <% end %>
  <% unless signed_in? %>
    <div id="signin_window_toggler"></div>
  <% end %>
</div>

app/views/layouts/_footer.erb
<div id="footer">
  <div class="float_left">

  </div>
  <%= form_tag locale_path, class: 'locale float_right' do %>
    <%= select_tag :set_locale, options_for_select(LANGUAGES.map{|l| [t(l[0]), l[1]]}, I18n.locale.to_s), onchange: 'this.form.submit()' %>
    <%= submit_tag 'submit' %>
    <%= javascript_tag "j('.locale input').hide()" %>
  <% end %>
</div>

app/views/layouts/_header.erb
<div id="header">
  <div style="margin-left: auto; margin-right: auto; width: 1100px;">
    <% if signed_in? %>
    <div class="float_left" id="admin_links">
      <%= link_to "Сообщения", feedbacks_path %>
      <%= link_to(t('orders') + " (#{@new_orders_count.to_s})", orders_path) %>
      <%= link_to t('categories'), categories_path %>
      <%= link_to t('products_list'), products_path %>
      <%= link_to t('profile'), admin_profile_path %>
      <%= link_to t('sign_out'), signout_path, :method => :delete %>
    </div>
    <% else %>
      <div class="float_right">
        <%= link_to t('feedback'), new_feedback_path %>
        <%= link_to t('cart'), cart_path(@cart) %>
        <%= link_to t('catalog'), catalog_path %>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/flash_messages'%>
<%= render 'shared/signin_window'  %>



app/views/layouts/_sidebar.erb
<div id="sidebar">
  <div class="sidebar_box">
    <h3 class="sidebar_title"><%= t("products_categories") %></h3>
    <% @categories.each do |cat| %>
      <%= link_to raw(cat.name + "<span class='count'>#{cat.products.length}</span>"),
                  "/catalog?category=#{cat.id}",
                  class: "item #{"active" if params[:category] == cat.id.to_s}" %>
    <% end if @categories%>
  </div>

  <div class="sidebar_box" id="sidebar_cart">
    <%= render "shared/cart" %>
  </div>
</div>


app/views/layouts/_styles_&_scripts.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script type="text/javascript" src="jquery.blend.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'menu.scss', :media => 'all' %>
<%= stylesheet_link_tag 'main.scss', :media => 'all' %>
<%= javascript_include_tag 'application', :media => 'all' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag 'main', :media => 'all' %>
    <%= javascript_include_tag 'application', :media => 'all' %>
    <%= favicon_link_tag %>
  </head>
  <body>
    <%= render 'layouts/header'%>
    <div id="main">
      <%= render 'layouts/cap' %>
      <div id="content">
        <%= yield %>
      </div>
      <%= render 'layouts/sidebar' if render_sidebar?%>
      <div class="cleaner"></div>
    </div>
    <div class="cleaner"></div>
    <%= render 'layouts/footer' %>
  </body>
</html>